import {test,expect} from '@playwright/test';
test('five Boos, voice cancellation, sensors, import/export and responsive layout',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('canvas')).toBeVisible({timeout:45000});
 await expect(page.getByText('Loading your Boo V2 CAD model…')).toHaveCount(0,{timeout:45000});
 for(let i=1;i<5;i++)await page.getByRole('button',{name:`Add Boo · ${i}/5`}).click();
 await expect(page.getByRole('button',{name:'Add Boo · 5/5'})).toBeDisabled();
 await page.getByRole('button',{name:'☀ Wake up'}).click();
 await page.getByRole('button',{name:/Boo 1 Waiting/}).click();
 await expect(page.getByRole('button',{name:/Boo 5 Wake up/})).toBeVisible();
 await page.getByRole('slider',{name:'Left hand',exact:true}).fill('90');
 await expect(page.getByRole('slider',{name:'Left hand',exact:true})).toHaveValue('90');
 await page.getByRole('tab',{name:'Body',exact:true}).click();
 await page.getByRole('button',{name:'Sitting',exact:true}).click();
 await expect(page.getByRole('slider',{name:'Lean',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Sleep on back',exact:true}).click();
 await page.getByRole('button',{name:'Sleep on belly',exact:true}).click();
 await page.getByRole('slider',{name:'Lift above surface',exact:true}).fill('0.3');
 await page.getByRole('button',{name:'Drop to surface'}).click();
 await page.getByRole('button',{name:'Reset Boo 1',exact:true}).click();
 await expect(page.locator('.time')).toHaveText('0.0 / 0.0s');
 await page.getByRole('tab',{name:'Voice & Hearing',exact:true}).click();
 await page.getByLabel('Mute all audio').check();await page.getByLabel('Selected Boo only').check();
 await page.getByRole('button',{name:'Hello Boo',exact:true}).click();
 await page.getByRole('tab',{name:'Joints',exact:true}).click();
 await page.getByRole('slider',{name:'Left hand',exact:true}).fill('42');
 await page.getByRole('tab',{name:'Voice & Hearing',exact:true}).click();
 await expect(page.getByRole('button',{name:'Hello Boo',exact:true})).toBeEnabled({timeout:8000});
 await expect(page.locator('.voice-events')).not.toContainText('→');
 await page.getByRole('button',{name:'Hello Boo',exact:true}).click();
 await expect(page.locator('.voice-events')).toContainText('Boo 1 · Hello Boo →',{timeout:8000});
 await page.getByRole('tab',{name:'Sensors',exact:true}).click();
 await page.getByRole('button',{name:'Tap head',exact:true}).click();
 await expect(page.getByRole('switch',{name:'Hold head touch'})).toHaveAttribute('aria-checked','true');
 await expect(page.getByRole('switch',{name:'Hold head touch'})).toHaveAttribute('aria-checked','false',{timeout:3000});
 const ids=await page.locator('[id]').evaluateAll(els=>els.map(e=>e.id));expect(new Set(ids).size).toBe(ids.length);
 await page.getByRole('tab',{name:'Sequence',exact:true}).click();
 await page.getByRole('button',{name:'Capture pose'}).click();await page.getByRole('button',{name:'Capture pose'}).click();
 await page.getByRole('button',{name:'Play sequence'}).click();await expect(page.getByRole('button',{name:'Pause',exact:true})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export',exact:true}).click();await (await download).saveAs('outputs/browser-tests/movement.json');
 await page.locator('input[type=file]').setInputFiles('outputs/browser-tests/movement.json');await expect(page.locator('.feedback')).toContainText('Movement imported');
 await page.getByRole('button',{name:'Remove Boo 1'}).click();await expect(page.getByRole('button',{name:'Add Boo · 4/5'})).toBeEnabled();
 for(const width of [1440,390]){await page.setViewportSize({width,height:900});await page.getByRole('tab',{name:'Voice & Hearing',exact:true}).click();await page.locator('.control-content:not([hidden])').evaluate(el=>el.scrollTop=el.scrollHeight);const box=await page.locator('canvas').boundingBox();expect(box).not.toBeNull();expect(box!.y).toBeGreaterThanOrEqual(0);expect(box!.y+box!.height).toBeLessThanOrEqual(900);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`outputs/browser-tests/layout-${width}.png`});}
 expect(errors).toEqual([]);
});
