'use client';
import {useEffect,useRef,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {BOO_METRICS,PLAY} from './metrics';
import {JOINTS,type Pose} from './motion';
import type {Hardware,Telemetry,Zone} from './hardware';
type Props={hardware:Hardware;setHardware:React.Dispatch<React.SetStateAction<Hardware>>;telemetry:Telemetry;bodyYaw:number;bodyX:number;bodyZ:number;onCommand:(key:keyof Pose,v:number)=>void};
export default function HardwarePanel({hardware:h,setHardware:set,telemetry:t,bodyYaw,bodyX,bodyZ,onCommand}:Props){
 const [feed,setFeed]=useState<{id:number;time:string;text:string}[]>([]),[freeze,setFreeze]=useState(false);const last=useRef(''),id=useRef(0),timers=useRef<Partial<Record<Zone,ReturnType<typeof setTimeout>>>>({});
 const push=(text:string)=>setFeed(f=>[{id:++id.current,time:new Date().toLocaleTimeString(),text},...f].slice(0,60));
 useEffect(()=>{const key=JSON.stringify([h.touch,t.radar.state,t.servos.map(s=>s.status),h.imuEnabled]);if(last.current!==key){if(!freeze){push(`Touch H/B/Belly: ${+h.touch.head}/${+h.touch.back}/${+h.touch.belly} · Radar: ${t.radar.state} · Servos: ${t.servos.map(s=>s.status).join(', ')}`);}last.current=key;}},[h.touch,h.imuEnabled,t.radar.state,t.servos,freeze]);
 useEffect(()=>()=>Object.values(timers.current).forEach(clearTimeout),[]);
 function touch(zone:Zone,value:boolean){clearTimeout(timers.current[zone]);set(p=>({...p,touch:{...p.touch,[zone]:value}}));}
 function tap(zone:Zone){touch(zone,true);timers.current[zone]=setTimeout(()=>set(p=>({...p,touch:{...p.touch,[zone]:false}})),700);}
 function exportFeed(){const url=URL.createObjectURL(new Blob([JSON.stringify({simulated:true,metrics:BOO_METRICS,playObjects:PLAY,latest:t,hardware:h,events:feed},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='boo-sensor-snapshot.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
 return <section className="hardware-panel"><div className="body-heading"><div><span className="overline">SENSORS & ACTUATORS / LIVE SIMULATION</span><h2>What Boo senses. What Boo does.</h2><p className="muted">All values are simulated. No physical hardware is connected. Telemetry refreshes at 10 Hz.</p></div><span className="badge">{t.time.toFixed(1)} s · simulation time</span></div><div className="sensor-grid">
 <article><h3>Touch under the skin</h3><p className="muted">Three digital zones. Hold a zone on, tap it, or press Boo in 3D.</p><label className="toggle-row"><span>Touch mode in 3D</span><Switch checked={h.touchMode} onCheckedChange={v=>set(p=>({...p,touchMode:v}))}/></label>{(['head','back','belly'] as Zone[]).map(zone=><div className="touch-row" key={zone}><span className={'signal '+(h.touch[zone]?'active':'')}/><strong>{zone}</strong><output>{h.touch[zone]?'TOUCHED · 1':'RELEASED · 0'}</output><Switch aria-label={'Hold '+zone+' touch'} checked={h.touch[zone]} onCheckedChange={v=>touch(zone,v)}/><button onClick={()=>tap(zone)}>Tap {zone}</button></div>)}<p className="muted">In touch mode, press and hold a skin zone; release to clear it. Turn touch mode off to drag Boo. Sensor type and thresholds are not specified.</p></article>
 <article><div className="sensor-title"><h3>MPU6050 · IMU</h3><Switch aria-label="Enable IMU" checked={h.imuEnabled} onCheckedChange={v=>set(p=>({...p,imuEnabled:v}))}/></div><p className="muted">Torso mounted. X = right, Y = up, Z = forward.</p><div className="readings">{['Lean X','Turn Y · relative','Roll Z'].map((s,i)=><div key={s}><span>{s}</span><strong>{h.imuEnabled?t.orientation[i].toFixed(1)+'°':'—'}</strong></div>)}</div><Table><TableHeader><TableRow><TableHead>Signal</TableHead><TableHead>X</TableHead><TableHead>Y</TableHead><TableHead>Z</TableHead></TableRow></TableHeader><TableBody>{[['Accel · m/s²',t.accel],['Gyro · °/s',t.gyro]].map(([name,values])=><TableRow key={name as string}><TableCell>{name as string}</TableCell>{(values as number[]).map((v,i)=><TableCell key={i}>{h.imuEnabled?v.toFixed(2):'—'}</TableCell>)}</TableRow>)}</TableBody></Table><p className="muted">{h.imuEnabled?(t.clipped?'Range clipped: ±16 g / ±2000°/s.':'Streaming · gravity included in acceleration.'):'Sensor disabled.'} Orientation is derived from scene motion; relative yaw has no compass reference.</p><button onClick={()=>set(p=>({...p,yawZero:bodyYaw}))}>Zero relative yaw</button></article>
 <article><div className="sensor-title"><h3>LD2420 · human detection</h3><Switch aria-label="Enable radar" checked={h.radarEnabled} onCheckedChange={v=>set(p=>({...p,radarEnabled:v}))}/></div><div className={'radar-status '+(t.radar.detected?'detected':'')}>{t.radar.state}</div><div className="readings"><div><span>Scene distance</span><strong>{h.human.enabled?t.radar.distance.toFixed(2)+' m':'—'}</strong></div><div><span>Moving target range</span><strong>{t.radar.movingDistance===null?'—':t.radar.movingDistance.toFixed(2)+' m'}</strong></div></div><label className="toggle-row">Human in scene<Switch checked={h.human.enabled} onCheckedChange={v=>set(p=>({...p,human:{...p.human,enabled:v}}))}/></label><label className="toggle-row">Human walking (±0.8 m)<Switch checked={h.human.moving} onCheckedChange={v=>set(p=>({...p,human:{...p.human,moving:v}}))}/></label>{(['x','z'] as const).map(axis=><div className="env-control" key={axis}><label id={'human-'+axis}>Human {axis.toUpperCase()} · {h.human[axis].toFixed(1)} m</label><Slider aria-labelledby={'human-'+axis} min={-8} max={8} step={.1} value={[h.human[axis]]} onValueChange={v=>set(p=>({...p,human:{...p.human,[axis]:Array.isArray(v)?v[0]:v}}))}/></div>)}<div className="env-control"><label id="radar-range">Range · {h.range.toFixed(1)} m</label><Slider aria-labelledby="radar-range" min={.5} max={6} step={.1} value={[h.range]} onValueChange={v=>set(p=>({...p,range:Array.isArray(v)?v[0]:v}))}/></div><div className="posture-buttons"><button onClick={()=>{const r=bodyYaw*Math.PI/180;set(p=>({...p,human:{...p.human,enabled:true,x:bodyX+Math.sin(r)*3,z:bodyZ+Math.cos(r)*3}}));}}>Person 3 m along floor</button><button onClick={()=>set(p=>({...p,human:{...p.human,enabled:false}}))}>Remove person</button></div><p className="muted">Live person: X {t.humanPosition.x.toFixed(2)} m / Z {t.humanPosition.z.toFixed(2)} m. Torso front mount; idealized ±60° cone, 0.2–6 m. Scene distance is ground truth, not stationary radar ranging. No wall or fabric attenuation. Real scale: Boo is approximately 224 mm high when belly-sleeping; the human is 1.75 m tall. One scene unit = 1 m.</p></article></div>
 <article className="servo-panel"><div className="body-heading"><div><h3>Feetech SCS0009 · five serial servos</h3><p className="muted">Joint sliders command targets; the 3D model follows simulated actual angles.</p></div><button onClick={()=>set(p=>({...p,servos:Object.fromEntries(JOINTS.map(j=>[j.key,{enabled:false,blocked:false}])) as Hardware['servos']}))}>Disable all torque</button></div><div className="servo-settings"><div className="env-control"><label id="servo-rate">Rate · {h.servoSpeed}°/s</label><Slider aria-labelledby="servo-rate" min={20} max={600} step={10} value={[h.servoSpeed]} onValueChange={v=>set(p=>({...p,servoSpeed:Array.isArray(v)?v[0]:v}))}/></div><div className="env-control"><label id="servo-voltage">Supply · {h.voltage.toFixed(1)} V</label><Slider aria-labelledby="servo-voltage" min={4.8} max={6} step={.1} value={[h.voltage]} onValueChange={v=>set(p=>({...p,voltage:Array.isArray(v)?v[0]:v}))}/></div></div><Table><TableHeader><TableRow>{['ID / joint','Target / actual shaft','Speed','Load*','Supply','Temp*','State','Torque','Block test','Command'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{t.servos.map((s,i)=><TableRow key={s.key}><TableCell>{i+1} · {JOINTS[i].label}</TableCell><TableCell>{s.target.toFixed(1)}° / {s.angle.toFixed(1)}°</TableCell><TableCell>{s.speed.toFixed(0)}°/s</TableCell><TableCell>{s.load.toFixed(0)}%</TableCell><TableCell>{h.voltage.toFixed(1)} V</TableCell><TableCell>{s.temperature.toFixed(1)}°C</TableCell><TableCell>{s.status}</TableCell><TableCell><Switch aria-label={'Torque '+JOINTS[i].label} checked={h.servos[s.key].enabled} onCheckedChange={v=>set(p=>({...p,servos:{...p.servos,[s.key]:{...p.servos[s.key],enabled:v}}}))}/></TableCell><TableCell><Switch aria-label={'Block '+JOINTS[i].label} checked={h.servos[s.key].blocked} onCheckedChange={v=>set(p=>({...p,servos:{...p.servos,[s.key]:{...p.servos[s.key],blocked:v}}}))}/></TableCell><TableCell><button onClick={()=>onCommand(s.key,JOINTS[i].max)}>Test move</button></TableCell></TableRow>)}</TableBody></Table><p className="muted">*Load and temperature are illustrative model values, not torque or thermal predictions. Block a joint then command a move to trigger protection after 2 s; toggle its torque off/on to clear it. Torque-off freezes the displayed joint; passive motion is not modeled. Provisional linkage: shaft = 150° + joint; eyelids = 90–150°. Calibrate to your actual installation.</p></article>
 <article className="event-panel"><div className="body-heading"><h3>Live event feed</h3><div className="posture-buttons"><button onClick={()=>setFreeze(v=>!v)}>{freeze?'Resume feed':'Pause feed'}</button><button onClick={()=>setFeed([])}>Clear feed</button><button onClick={exportFeed}>Export snapshot</button></div></div><p className="muted">Most recent 60 state changes. Pausing the feed does not pause Boo.</p><div className="event-list">{feed.length?feed.map(e=><div key={e.id}><time>{e.time}</time><span>{e.text}</span></div>):<p>No recorded events.</p>}</div></article><p className="source-note">Hardware references: <a href="https://www.hlktech.com/en/Goods-246.html" target="_blank" rel="noreferrer">Hi-Link LD2420</a> · <a href="https://learn.adafruit.com/mpu6050-6-dof-accelerometer-and-gyro?view=all" target="_blank" rel="noreferrer">MPU6050</a> · <a href="https://pages.switch-science.com/comparison/files/feetech/serial-scs/SCS0009_datasheet.pdf" target="_blank" rel="noreferrer">Feetech SCS0009</a></p></section>;
}
