'use client';
import {useEffect,useRef,useState} from 'react';
import {Slider} from '@/components/ui/slider';
import {Moon,Play,Pause,RotateCcw,Plus,Download,Upload,Hand,Focus,ChevronRight} from 'lucide-react';
import Scene from './Scene';
import {useBooTools} from './useBooTools';
import {REST,JOINTS,PRESETS,sample,validPose,type Pose,type Frame} from './motion';
export default function Home(){
 const [pose,setPose]=useState<Pose>({...REST}),[frames,setFrames]=useState<Frame[]>([]),[mode,setMode]=useState('Manual'),[running,setRunning]=useState(false),[time,setTime]=useState(0),[speed,setSpeed]=useState(1),[duration,setDuration]=useState(1.5),[tracking,setTracking]=useState(false),[targetX,setTargetX]=useState(0),[targetY,setTargetY]=useState(1.8),[ballX,setBallX]=useState(.57),[ballZ,setBallZ]=useState(.7),[reset,setReset]=useState(0),[camera,setCamera]=useState(0),[message,setMessage]=useState('Boo is resting. Move a joint or try a movement.');
 const sequence=useRef<Frame[]>([]),clock=useRef(0),upload=useRef<HTMLInputElement>(null),lastUI=useRef(0);const total=sequence.current.slice(0,-1).reduce((n,f)=>n+f.duration,0);
 function play(name:string,seq:Frame[]){if(seq.length<2){setMessage('Capture at least two poses to play a sequence.');return;}sequence.current=seq;clock.current=0;setTime(0);setMode(name);setTracking(false);setPose({...seq[0].pose});setRunning(true);setMessage(name+' is playing.');}
 function manual(key:keyof Pose,v:number){setRunning(false);setTracking(false);setMode('Manual');setPose(p=>({...p,[key]:v}));}
 useEffect(()=>{if(!running)return;let raf=0,last=performance.now();const tick=(now:number)=>{clock.current+=Math.min((now-last)/1000,.05)*speed;last=now;const end=sequence.current.slice(0,-1).reduce((n,f)=>n+f.duration,0);setPose(sample(sequence.current,Math.min(clock.current,end)));if(now-lastUI.current>70){setTime(clock.current);lastUI.current=now;}if(clock.current>=end){setTime(end);setRunning(false);setMessage('Movement complete.');return;}raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[running,speed]);
 useEffect(()=>{if(!tracking)return;setPose(p=>({...p,turn:Math.max(-65,Math.min(65,Math.atan2(targetX,2)*180/Math.PI)),tilt:Math.max(-25,Math.min(50,-Math.atan2(targetY-1.94,Math.hypot(targetX,2))*180/Math.PI)),lids:20}));},[tracking,targetX,targetY]);
 useBooTools(pose,p=>{setRunning(false);setTracking(false);setMode('Manual');setPose(p);},name=>play(name,PRESETS[name]));
 function resetAll(){setRunning(false);setTracking(false);setMode('Manual');setPose({...REST});clock.current=0;setTime(0);setReset(n=>n+1);setMessage('Resting pose and ball reset.');}
 function save(){const data={name:'Boo movement',version:1,dofs:5,frames};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='boo-movement.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Movement exported.');}
 async function importFile(file?:File){if(!file)return;try{if(file.size>200000)throw Error();const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.frames)||data.frames.length>100||!data.frames.every((f:Frame)=>validPose(f.pose)&&Number.isFinite(f.duration)&&f.duration>=.2&&f.duration<=10))throw Error();setFrames(data.frames);setMessage('Movement imported. Press Play sequence to run it.');}catch{setMessage('Could not import: choose a Boo movement file with valid joint ranges and timing.');}if(upload.current)upload.current.value='';}
 return <main><header><div className="brand"><span className="brand-icon"><Moon size={23}/></span><div><h1>Boo <span>motion lab</span></h1><p>Companion robot · 5 degrees of freedom</p></div></div><div className="header-right"><span className="badge">Concept simulation</span><button onClick={resetAll}><RotateCcw size={16}/> Reset</button></div></header>
 <div className="workspace"><section className="viewport"><div className="view-head"><span className="overline">01 / PLAY SPACE</span><span className="status"><i/>{running?mode:tracking?'Following target':'Ready to explore'}</span></div><Scene pose={pose} world={{targetX,targetY,ballX,ballZ,reset,camera,paused:false}} onContact={setMessage}/><div className="view-footer"><span>Drag to orbit · Scroll to zoom · Right-drag to pan</span><button onClick={()=>setCamera(n=>n+1)}><Focus size={16}/> Recenter</button></div><div className="transport"><button className={running?'':'primary'} onClick={()=>{if(running)setRunning(false);else if(sequence.current.length>1&&clock.current<total)setRunning(true);else if(sequence.current.length>1)play(mode,sequence.current);else play('Wake up',PRESETS['Wake up']);}}>{running?<Pause size={17}/>:<Play size={17}/>} {running?'Pause':'Play'}</button><div className="progress"><div style={{width:total?`${Math.min(time/total,1)*100}%`:'0%'}}/></div><span className="time">{time.toFixed(1)} / {total.toFixed(1)}s</span><button onClick={()=>setSpeed(s=>s===.5?1:s===1?1.5:.5)} aria-label="Change playback speed">{speed}×</button></div><p className="feedback" role="status">{message}</p></section>
 <aside><div className="panel-title"><span className="overline">02 / JOINT CONTROLS</span><span className="tiny">5 DOF</span></div><h2>A little movement.<br/>A lot of personality.</h2><p className="muted">Boo’s left and right follow Boo’s perspective.</p><div className="joints">{JOINTS.map(j=><div className="joint" key={j.key}><div><label id={'label-'+j.key}>{j.label}</label><output>{Math.round(pose[j.key])}{j.unit}</output></div><Slider aria-labelledby={'label-'+j.key} value={[pose[j.key]]} min={j.min} max={j.max} step={1} onValueChange={v=>manual(j.key,Array.isArray(v)?v[0]:v)}/><div className="limits"><span>{j.key==='lids'?'Open':j.min+'°'}</span><span>{j.key==='lids'?'Closed':j.max+'°'}</span></div></div>)}</div><div className="divider"/><span className="overline">MOVEMENT LIBRARY</span><div className="presets">{Object.keys(PRESETS).map((name,i)=><button key={name} onClick={()=>play(name,PRESETS[name])}><span>{i===0?'☀':i===1?'↗':i===2?'↔':'☾'}</span>{name}<ChevronRight size={15}/></button>)}</div></aside></div>
 <div className="bottom"><section className="sequence"><div className="section-top"><div><span className="overline">03 / COMPOSE A MOVEMENT</span><h2>Your pose sequence</h2></div><button className="primary" disabled={frames.length>=100} onClick={()=>{setFrames(f=>[...f,{pose:{...pose},duration}]);setMessage('Pose captured. Adjust joints and capture the next pose.');}}><Plus size={16}/> Capture pose</button></div><p className="muted">Set joints above, capture poses, then play the transitions in order.</p><div className="frames">{frames.length===0?<div className="empty">Your first pose starts here. <span>Each pose stores all five joint positions.</span></div>:frames.map((f,i)=><div className="frame" key={i}><button className="pose-preview" onClick={()=>{setRunning(false);setTracking(false);setMode('Manual');setPose({...f.pose});setMessage('Pose '+(i+1)+' loaded.');}}><span>{String(i+1).padStart(2,'0')}</span><Hand size={20}/><small>{i===frames.length-1?'Final pose':f.duration+'s →'}</small></button><button className="remove" aria-label={'Remove pose '+(i+1)} onClick={()=>setFrames(fs=>fs.filter((_,n)=>n!==i))}>×</button></div>)}</div><div className="sequence-tools"><label>Transition <input type="number" min="0.2" max="10" step="0.1" value={duration} onChange={e=>setDuration(Math.min(10,Math.max(.2,Number(e.target.value)||.2)))}/> s</label><button disabled={frames.length<2} onClick={()=>play('Your sequence',frames)}><Play size={15}/> Play sequence</button><button disabled={!frames.length} onClick={save}><Download size={15}/> Export</button><button onClick={()=>upload.current?.click()}><Upload size={15}/> Import</button><input ref={upload} hidden type="file" accept="application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/></div></section>
 <section className="environment"><span className="overline">04 / ENVIRONMENT</span><h2>Give Boo something to notice.</h2><button className={tracking?'primary':''} aria-pressed={tracking} onClick={()=>{setTracking(v=>!v);setRunning(false);setMode('Target');setMessage(tracking?'Target following off.':'Boo is looking at the gold target.');}}><Focus size={16}/>{tracking?'Following target':'Follow target'}</button><div className="env-control"><label id="target-x">Target · left / right</label><Slider aria-labelledby="target-x" min={-2} max={2} step={.05} value={[targetX]} onValueChange={v=>setTargetX(Array.isArray(v)?v[0]:v)}/></div><div className="env-control"><label id="target-y">Target · height</label><Slider aria-labelledby="target-y" min={.3} max={3} step={.05} value={[targetY]} onValueChange={v=>setTargetY(Array.isArray(v)?v[0]:v)}/></div><div className="ball-actions"><span className="muted">Place the ball within reach:</span><button onClick={()=>{setBallX(.57);setBallZ(.7);setReset(n=>n+1);}}>Left hand</button><button onClick={()=>{setBallX(-.57);setBallZ(.7);setReset(n=>n+1);}}>Right hand</button></div><p className="muted">Raise a hand slowly to nudge the ball. It falls, bounces, and stops at the room edges.</p></section></div><footer>Provisional plush geometry and joint ranges. Hand joints swing the whole arm; feet remain fixed. Ball physics are approximate. This model does not predict motor loads, fabric deformation, or hardware safety.</footer></main>;
}


