'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {addRoom} from './room';
import {surfaceAt} from './surfaces';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {bellyContact,contactPoints} from './contact';
import {buildV2} from './robotV2';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DRACOLoader} from 'three/addons/loaders/DRACOLoader.js';
import {PLAY,BOO_METRICS,GRAVITY,kineticEnergy} from './metrics';
import type {Pose} from './motion';
import {advanceDrop,sphereExtents,supportHeight,type BodyPose} from './body';
import {initialServos,stepServo,jointAngle,radarState,gyroRate,accelerometer,type Hardware,type Telemetry,type Zone} from './hardware';
export type World={targetX:number;targetY:number;ballX:number;ballZ:number;reset:number;camera:number;roomView:boolean;paused:boolean;human:Hardware['human']};
export type BooInstance={id:number;pose:Pose;body:BodyPose;hardware:Hardware;tracking:boolean;onContact:(s:string)=>void;onBodyChange:(b:BodyPose)=>void;onDragStart:()=>void;onTrackingPose:(p:Pose)=>void;onTouch:(zone:Zone,value:boolean)=>void;onTelemetry:(t:Telemetry)=>void};
export default function Scene({instances,selected,onSelect,world}:{instances:BooInstance[];selected:number;onSelect:(id:number)=>void;world:World}){
 const host=useRef<HTMLDivElement>(null),live=useRef({instances,selected,onSelect,world});useLayoutEffect(()=>{live.current={instances,selected,onSelect,world};});const [error,setError]=useState(''),[model,setModel]=useState<THREE.Group|null>(null);
 useEffect(()=>{let cancelled=false;const decoder=new DRACOLoader().setDecoderPath(import.meta.env.BASE_URL+'draco/');const loader=new GLTFLoader().setDRACOLoader(decoder);loader.load(import.meta.env.BASE_URL+'models/boo-v2.glb',g=>{if(!cancelled){try{setModel(g.scene);}catch(e){setError(String(e));}}decoder.dispose();},undefined,()=>{if(!cancelled)setError('Could not load Boo V2. Reload to retry.');decoder.dispose();});return()=>{cancelled=true;decoder.dispose();};},[]);
 useEffect(()=>{if(!host.current||!model)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{
 // WebGL allocation is an external operation; report its failure to the UI.
 // oxlint-disable-next-line react/react-compiler
 setError('3D is unavailable. Enable hardware acceleration or try another browser.');return;}
 const el=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#e6edf1');el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.Fog('#e6edf1',10,23);const camera=new THREE.PerspectiveCamera(38,1,.005,50);camera.position.set(.62,.46,.92);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,.18,0);orbit.enableDamping=true;orbit.minDistance=.3;orbit.maxDistance=18;orbit.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.HemisphereLight(0xffffff,0x74839a,2.6));const light=new THREE.DirectionalLight(0xfff6e4,4);light.position.set(-3,7,4);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-6,right:6,top:6,bottom:-6});scene.add(light);
 const mat=(c:string)=>new THREE.MeshStandardMaterial({color:c,roughness:.95});const cream=mat('#e8d8be'),blue=mat('#a8b4aa');
 function ell(parent:THREE.Object3D,m:THREE.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number){const o=new THREE.Mesh(new THREE.SphereGeometry(1,40,28),m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),mat('#e6e4df'));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);addRoom(scene);
 const rug=new THREE.Mesh(new THREE.CylinderGeometry(PLAY.rugRadius,PLAY.rugRadius,PLAY.rugTop,80),blue);rug.position.y=PLAY.rugTop/2;rug.receiveShadow=true;scene.add(rug);
  const human=new THREE.Group();scene.add(human);const humanMat=mat('#557acc');ell(human,humanMat,0,1.55,0,.17,.2,.17);ell(human,humanMat,0,1,0,.23,.38,.14);for(const side of [-1,1]){ell(human,humanMat,side*.12,.4,0,.08,.4,.09);ell(human,humanMat,side*.3,1,0,.08,.32,.08);}
 const table=new THREE.Mesh(new THREE.BoxGeometry(PLAY.tableWidth,PLAY.tableHeight,PLAY.tableDepth),mat('#c59670'));table.position.set(0,PLAY.tableHeight/2,PLAY.tableZ);table.castShadow=true;table.receiveShadow=true;scene.add(table);
 const ball=ell(scene,mat('#d56e46'),PLAY.ballX,PLAY.tableHeight+PLAY.ballRadius,PLAY.ballZ,PLAY.ballRadius,PLAY.ballRadius,PLAY.ballRadius);const stripe=new THREE.Mesh(new THREE.TorusGeometry(PLAY.ballRadius*1.005,.0015,8,40),cream);ball.add(stripe);stripe.scale.setScalar(1/PLAY.ballRadius);
 const target=ell(scene,mat('#d5a438'),0,PLAY.targetY,PLAY.targetZ,.01,.01,.01);const ring=new THREE.Mesh(new THREE.TorusGeometry(.02,.0015,8,40),mat('#b38726'));target.add(ring);ring.scale.setScalar(100);
 let frame=0,last=performance.now(),lastReset=-1,lastCamera=-1,lastRoomView:boolean|null=null,px=NaN,pz=NaN,worldTime=0;const vel=new THREE.Vector3();
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),dragPlane=new THREE.Plane(),hit=new THREE.Vector3(),offset=new THREE.Vector3();
 const setRay=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);};
 function createActor(id:number){
 const input=()=>live.current.instances.find(b=>b.id===id);
 const rig=new THREE.Group();scene.add(rig);const {boo,head,hands,supportMeshes,applyPose}=buildV2(model!.clone(true));rig.add(boo);
 const touchMarkers:Record<Zone,THREE.Mesh>={head:ell(head,mat('#96b6b9'),0,.10,.065,.012,.006,.012),belly:ell(boo,mat('#96b6b9'),0,-.10,0,.012,.006,.012),back:ell(boo,mat('#96b6b9'),0,.10,0,.012,.006,.012)};touchMarkers.head.position.copy(head.worldToLocal(boo.localToWorld(new THREE.Vector3(0,.12,.17))));Object.entries(touchMarkers).forEach(([zone,m])=>{m.userData.touchZone=zone;m.userData.sensorMarker=true;});
 const radarRoot=new THREE.Group();scene.add(radarRoot);const conePoints:THREE.Vector3[]=[];for(let i=0;i<=60;i++){const a=i/60*Math.PI*2;conePoints.push(new THREE.Vector3(Math.sin(a)*Math.sin(Math.PI/3),Math.cos(a)*Math.sin(Math.PI/3),.5));}for(let i=0;i<4;i++){const a=i*Math.PI/2;conePoints.push(new THREE.Vector3(),new THREE.Vector3(Math.sin(a)*Math.sin(Math.PI/3),Math.cos(a)*Math.sin(Math.PI/3),.5),new THREE.Vector3());}const cone=new THREE.Line(new THREE.BufferGeometry().setFromPoints(conePoints),new THREE.LineBasicMaterial({color:0x6c94ba,transparent:true,opacity:.18}));radarRoot.add(cone);
 const previous=[new THREE.Vector3(),new THREE.Vector3()];let initialized=false,lastContact=0;
 let bodyY=0,fallSpeed=0,wasFalling=false,dragging=false,pointerId=-1,lastBodyKey='',supportMin=0,contactPitch=0;
 let impactEnergy=0;let touching:Zone|null=null;let servoStates=initialServos(),sampleTime=0,simTime=0;const lastPosition=new THREE.Vector3(),lastVelocity=new THREE.Vector3(),lastOrientation=new THREE.Quaternion();let imuReady=false,lastHardwareReset=-1;const sampleAccel=new THREE.Vector3(),sampleGyro=new THREE.Vector3();let sampleDuration=0,sampleClipped=false;

 const halo=new THREE.Mesh(new THREE.RingGeometry(.23,.24,64),new THREE.MeshBasicMaterial({color:['#356b9a','#aa6042','#6a579d','#248475','#a27520'][id],side:THREE.DoubleSide,transparent:true,opacity:.9}));halo.rotation.x=-Math.PI/2;scene.add(halo);
 const labelCanvas=document.createElement('canvas');labelCanvas.width=256;labelCanvas.height=64;const ctx=labelCanvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,256,64);ctx.fillStyle='#20344d';ctx.font='bold 34px sans-serif';ctx.textAlign='center';ctx.fillText('Boo '+(id+1),128,45);const labelTexture=new THREE.CanvasTexture(labelCanvas);const label=new THREE.Sprite(new THREE.SpriteMaterial({map:labelTexture,depthTest:false}));label.scale.set(.18,.045,1);scene.add(label);
 const down=(event:PointerEvent,intersection:THREE.Intersection)=>{if(event.button!==0||dragging||touching)return;const current=input();if(!current)return;live.current.onSelect(id);if(input()!.hardware.touchMode){const local=boo.worldToLocal(intersection.point.clone());const zone=intersection.object.userData.touchZone as Zone|undefined;touching=zone??(intersection.object.userData.part==='main_body'?(local.y>0?'back':'belly'):null);if(!touching)return;event.preventDefault();event.stopImmediatePropagation();pointerId=event.pointerId;orbit.enabled=false;renderer.domElement.setPointerCapture(pointerId);input()!.onTouch(touching,true);return;}event.preventDefault();event.stopImmediatePropagation();dragging=true;pointerId=event.pointerId;orbit.enabled=false;renderer.domElement.setPointerCapture(pointerId);dragPlane.setFromNormalAndCoplanarPoint(new THREE.Vector3(0,1,0),intersection.point);offset.copy(rig.position).sub(intersection.point);input()!.onDragStart();input()!.onContact('Holding Boo · move to position, then release to drop.');renderer.domElement.style.cursor='grabbing';};
 const move=(event:PointerEvent)=>{if(!dragging||event.pointerId!==pointerId)return;event.preventDefault();event.stopImmediatePropagation();setRay(event);if(ray.ray.intersectPlane(dragPlane,hit)){const b=input()!.body;input()!.onBodyChange({...b,x:THREE.MathUtils.clamp(hit.x+offset.x,-3.5,3.5),z:THREE.MathUtils.clamp(hit.z+offset.z,-3.5,3.5)});}};
 const up=(event:PointerEvent)=>{if(touching&&event.pointerId===pointerId){event.preventDefault();event.stopImmediatePropagation();input()!.onTouch(touching,false);touching=null;orbit.enabled=true;if(renderer.domElement.hasPointerCapture(pointerId))renderer.domElement.releasePointerCapture(pointerId);return;}if(!dragging||event.pointerId!==pointerId)return;event.preventDefault();event.stopImmediatePropagation();dragging=false;orbit.enabled=true;if(renderer.domElement.hasPointerCapture(pointerId))renderer.domElement.releasePointerCapture(pointerId);renderer.domElement.style.cursor='grab';input()!.onBodyChange({...input()!.body,lift:0});input()!.onContact('Boo is settling onto the surface.');};
 function update(dt:number,now:number){const current=input();if(!current)return;const command=current.pose,w={...live.current.world,...current};const hw=w.hardware;if(hw.resetSerial!==lastHardwareReset){servoStates=initialServos();lastHardwareReset=hw.resetSerial;simTime=0;sampleTime=0;imuReady=false;bodyY=0;fallSpeed=0;wasFalling=false;lastBodyKey='';initialized=false;impactEnergy=0;sampleAccel.set(0,0,0);sampleGyro.set(0,0,0);sampleDuration=0;sampleClipped=false;}simTime+=dt;servoStates=servoStates.map(s=>stepServo(s,command[s.key],hw.servos[s.key],hw.servoSpeed*(hw.voltage/6),hw.voltage,dt));const p=Object.fromEntries(servoStates.map(s=>[s.key,jointAngle(s.key,s.angle)])) as Pose;
 Object.entries(touchMarkers).forEach(([zone,m])=>{const active=hw.touch[zone as Zone];m.visible=hw.touchMode||active;(m.material as THREE.MeshStandardMaterial).color.set(active?'#2dd792':'#96b6b9');(m.material as THREE.MeshStandardMaterial).emissive.set(active?'#08704c':'#000000');});
 applyPose(p,w.body);target.position.set(w.targetX,w.targetY,PLAY.targetZ);
  const b=w.body;rig.rotation.set(THREE.MathUtils.degToRad(b.pitch),THREE.MathUtils.degToRad(b.yaw),THREE.MathUtils.degToRad(b.roll),'YXZ');rig.position.set(b.x,0,b.z);rig.updateMatrixWorld(true);
 const bellyMode=Math.abs(b.pitch)<.001&&Math.abs(b.roll)<.001&&b.lift===0&&!dragging;
 const planted=bellyMode&&!wasFalling&&bodyY<=-supportMin+.002;
 const bodyKey=JSON.stringify([p,b.x,b.z,b.pitch,b.yaw,b.roll,b.legLeft,b.legRight,bellyMode]);if(bodyKey!==lastBodyKey){contactPitch=0;if(bellyMode){const stance=bellyContact(contactPoints(supportMeshes,rig),b.x,b.z,b.yaw);contactPitch=stance.pitch;supportMin=-stance.height;}else supportMin=-supportHeight(supportMeshes);lastBodyKey=bodyKey;}
 if(bellyMode)rig.rotation.x=THREE.MathUtils.degToRad(contactPitch);
 const groundY=-supportMin;if(planted)bodyY=groundY;const targetY=groundY+b.lift+(dragging?PLAY.dragLift:0);if(bodyY<targetY){bodyY=targetY;fallSpeed=0;}else if(bodyY>targetY+.0001){const next=advanceDrop(bodyY,fallSpeed,targetY,dt);if(next.landed)impactEnergy=kineticEnergy(Math.sqrt(fallSpeed*fallSpeed+2*GRAVITY*Math.max(0,bodyY-targetY)));bodyY=next.y;fallSpeed=next.v;wasFalling=true;}else{fallSpeed=0;if(wasFalling&&!dragging){current.onContact('Boo has landed · '+impactEnergy.toFixed(2)+' J impact energy (rigid approximation).');wasFalling=false;}}rig.position.y=bodyY;rig.updateMatrixWorld(true);
 if(w.tracking){const localTarget=boo.worldToLocal(target.position.clone()).sub(new THREE.Vector3(0,.06,.17));const turn=THREE.MathUtils.clamp(THREE.MathUtils.radToDeg(Math.atan2(localTarget.x,localTarget.z)),-43,46),tilt=THREE.MathUtils.clamp(-THREE.MathUtils.radToDeg(Math.atan2(localTarget.y,Math.hypot(localTarget.x,localTarget.z))),-25,50);if(Math.abs(turn-command.turn)>.2||Math.abs(tilt-command.tilt)>.2||command.lids!==20)current.onTrackingPose({...command,turn,tilt,lids:20});}
 hands.forEach((h,i)=>{const hp=h.getWorldPosition(new THREE.Vector3());if(!w.paused){const delta=ball.position.clone().sub(hp),distance=delta.length(),radius=PLAY.ballRadius+Math.max(...Object.values(sphereExtents(h.matrixWorld)));if(distance<radius){if(distance<.001)delta.set(0,0,1);else delta.normalize();ball.position.copy(hp).addScaledVector(delta,radius);const speed=initialized?THREE.MathUtils.clamp(hp.clone().sub(previous[i]).divideScalar(Math.max(dt,.001)).dot(delta),-1,1):0;// Effective hand mass assumes 5% of total mass; ball is a 30 g test object.
 const relative=speed-vel.dot(delta);if(relative>0)vel.addScaledVector(delta,1.25*(BOO_METRICS.mass*.05)/(BOO_METRICS.mass*.05+PLAY.ballMass)*relative);if(now-lastContact>550){current.onContact(i===0?'Left hand nudged the ball':'Right hand nudged the ball');lastContact=now;}}}previous[i].copy(hp);});initialized=true;
 const radarPosition=boo.localToWorld(new THREE.Vector3(0,.025,.15));radarRoot.position.copy(radarPosition);radarRoot.quaternion.copy(rig.quaternion);radarRoot.scale.setScalar(hw.range);radarRoot.visible=hw.radarEnabled&&live.current.selected===id;const radar=radarState({...hw,human:{...hw.human,x:human.position.x,z:human.position.z}},radarPosition,rig.quaternion);const personLocal=boo.worldToLocal(new THREE.Vector3(human.position.x,1,human.position.z)).sub(new THREE.Vector3(0,.06,.17));const humanAim={turn:THREE.MathUtils.clamp(THREE.MathUtils.radToDeg(Math.atan2(personLocal.x,personLocal.z)),-43,46),tilt:THREE.MathUtils.clamp(-THREE.MathUtils.radToDeg(Math.atan2(personLocal.y,Math.hypot(personLocal.x,personLocal.z))),-25,50)};
 const currentPosition=rig.position.clone();const velocity=imuReady?currentPosition.clone().sub(lastPosition).divideScalar(Math.max(dt,.001)):new THREE.Vector3();const linear=imuReady?velocity.clone().sub(lastVelocity).divideScalar(Math.max(dt,.001)):new THREE.Vector3();const accel=accelerometer(linear,rig.quaternion),gyro=imuReady?gyroRate(lastOrientation,rig.quaternion,dt):new THREE.Vector3();lastPosition.copy(currentPosition);lastVelocity.copy(velocity);lastOrientation.copy(rig.quaternion);imuReady=true;
 sampleDuration+=dt;sampleClipped ||= accel.toArray().some(v=>Math.abs(v)>16*9.81)||gyro.toArray().some(v=>Math.abs(v)>2000);sampleAccel.addScaledVector(accel.clone().clampScalar(-16*9.81,16*9.81),dt);sampleGyro.addScaledVector(gyro.clone().clampScalar(-2000,2000),dt);if(simTime-sampleTime>=.1){sampleTime=simTime;const rawAccel=sampleAccel.clone().divideScalar(sampleDuration).toArray(),rawGyro=sampleGyro.clone().divideScalar(sampleDuration).toArray();current.onTelemetry({time:simTime,actual:p,servos:servoStates.map(s=>({...s})),accel:rawAccel.map(v=>THREE.MathUtils.clamp(v,-16*9.81,16*9.81)),gyro:rawGyro.map(v=>THREE.MathUtils.clamp(v,-2000,2000)),orientation:[THREE.MathUtils.radToDeg(rig.rotation.x),((b.yaw-hw.yawZero+540)%360)-180,b.roll],clipped:sampleClipped,radar,humanPosition:{x:human.position.x,z:human.position.z},humanAim,bodyHeight:bodyY,lift:Math.max(0,bodyY-groundY),fallSpeed,impactEnergy});sampleAccel.set(0,0,0);sampleGyro.set(0,0,0);sampleDuration=0;sampleClipped=false;}

 halo.position.set(w.body.x,.014,w.body.z);halo.material.opacity=live.current.selected===id?.95:.25;label.position.set(w.body.x,bodyY+.26,w.body.z);label.material.opacity=live.current.selected===id?1:.7;
 }
 return {boo,down,move,up,update,setVisible:(v:boolean)=>{rig.visible=v;halo.visible=v;label.visible=v;radarRoot.visible=false;},cancel:()=>{if(!touching&&!dragging)return;if(renderer.domElement.hasPointerCapture(pointerId))renderer.domElement.releasePointerCapture(pointerId);if(touching)input()?.onTouch(touching,false);touching=null;dragging=false;orbit.enabled=true;},dispose:()=>{labelTexture.dispose();}};
 }
 const actors=new Map<number,ReturnType<typeof createActor>>();let captured:ReturnType<typeof createActor>|undefined;
 const down=(event:PointerEvent)=>{if(event.button!==0||captured)return;setRay(event);const hits=ray.intersectObjects(live.current.instances.flatMap(b=>actors.get(b.id)?.boo??[]),true).filter(hit=>{let o:THREE.Object3D|null=hit.object;while(o){if(!o.visible)return false;o=o.parent;}const m=(hit.object as THREE.Mesh).material;return !m||(Array.isArray(m)?m.some(v=>v.visible):m.visible);});if(!hits.length)return;const actor=[...actors.values()].find(a=>{let o:THREE.Object3D|null=hits[0].object;while(o){if(o===a.boo)return true;o=o.parent;}return false;});if(actor){captured=actor;actor.down(event,hits[0]);}};
 const move=(event:PointerEvent)=>captured?.move(event);
 const up=(event:PointerEvent)=>{captured?.up(event);captured=undefined;};
 renderer.domElement.style.cursor='grab';renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move,true);renderer.domElement.addEventListener('pointerup',up,true);renderer.domElement.addEventListener('pointercancel',up,true);
 const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 function tick(now:number){if(document.hidden){last=now;frame=requestAnimationFrame(tick);return;}const dt=Math.min((now-last)/1000,.04);last=now;worldTime+=dt;const w=live.current.world;
 human.visible=w.human.enabled;human.position.set(THREE.MathUtils.clamp(w.human.x+(w.human.moving?Math.sin(worldTime*.6)*.8:0),-8,8),0,w.human.z);human.rotation.y=w.human.moving?Math.sin(worldTime*3)*.12:0;
 target.position.set(w.targetX,w.targetY,PLAY.targetZ);
 if(w.reset!==lastReset||w.ballX!==px||w.ballZ!==pz){ball.position.set(w.ballX,PLAY.tableHeight+PLAY.ballRadius,w.ballZ);vel.set(0,0,0);lastReset=w.reset;px=w.ballX;pz=w.ballZ;}
 for(const [id,actor] of actors){const visible=live.current.instances.some(b=>b.id===id);actor.setVisible(visible);if(!visible){actor.cancel();if(captured===actor)captured=undefined;}}
 for(const instance of live.current.instances){let actor=actors.get(instance.id);if(!actor){actor=createActor(instance.id);actors.set(instance.id,actor);}actor.update(dt,now);}
 if(w.camera!==lastCamera||w.roomView!==lastRoomView){const bounds=new THREE.Box3();for(const b of live.current.instances)bounds.expandByObject(actors.get(b.id)!.boo);const center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const distance=Math.max(.9,size.length()/(2*Math.sin(THREE.MathUtils.degToRad(38)/2))*Math.max(1,1/camera.aspect)*1.15);orbit.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(.62,.46,.92).normalize().multiplyScalar(distance));if(w.roomView){const distance=5.5/(2*Math.tan(THREE.MathUtils.degToRad(38)/2)*Math.min(1,camera.aspect));orbit.target.set(0,.35,-.55);camera.position.copy(orbit.target).add(new THREE.Vector3(.5,.7,1).normalize().multiplyScalar(distance));}lastRoomView=w.roomView;lastCamera=w.camera;}
 if(!w.paused){const oldY=ball.position.y;vel.y-=GRAVITY*dt;ball.position.addScaledVector(vel,dt);const surface=surfaceAt(ball.position.x,ball.position.z,oldY-PLAY.ballRadius+.002)+PLAY.ballRadius;if(ball.position.y<surface){ball.position.y=surface;vel.y=Math.abs(vel.y)<.15?0:-vel.y*.42;vel.x*=Math.exp(-1.5*dt);vel.z*=Math.exp(-1.5*dt);}for(const axis of ['x','z'] as const){if(Math.abs(ball.position[axis])>(4.76-PLAY.ballRadius)){ball.position[axis]=Math.sign(ball.position[axis])*(4.76-PLAY.ballRadius);vel[axis]*=-.6;}}ball.rotation.x+=vel.z*dt/PLAY.ballRadius;ball.rotation.z-=vel.x*dt/PLAY.ballRadius;}
 orbit.update();renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
 frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);renderer.domElement.removeEventListener('pointerdown',down,true);renderer.domElement.removeEventListener('pointermove',move,true);renderer.domElement.removeEventListener('pointerup',up,true);renderer.domElement.removeEventListener('pointercancel',up,true);observer.disconnect();orbit.dispose();actors.forEach(a=>a.dispose());const geometries=new Set<THREE.BufferGeometry>(),materials=new Set<THREE.Material>();scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line||o instanceof THREE.Sprite){if('geometry' in o)geometries.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>materials.add(m));}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());renderer.dispose();el.removeChild(renderer.domElement);};
 },[model]);
 return <div ref={host} className="scene" aria-label="Interactive 3D model of Boo, a five-joint plush sloth">{!model&&!error&&<p className="feedback">Loading your Boo V2 CAD model…</p>}{error&&<p className="error">{error}</p>}</div>;
}





