'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {Pose} from './motion';
import {advanceDrop,sphereExtents,type BodyPose} from './body';
import {initialServos,stepServo,jointAngle,radarState,gyroRate,accelerometer,type Hardware,type Telemetry,type Zone} from './hardware';
export type World={targetX:number;targetY:number;ballX:number;ballZ:number;reset:number;camera:number;paused:boolean;tracking:boolean;body:BodyPose;hardware:Hardware};
export default function Scene({pose,world,onContact,onBodyChange,onDragStart,onTrackingPose,onTouch,onTelemetry}:{pose:Pose;world:World;onContact:(s:string)=>void;onBodyChange:(b:BodyPose)=>void;onDragStart:()=>void;onTrackingPose:(p:Pose)=>void;onTouch:(zone:Zone,value:boolean)=>void;onTelemetry:(t:Telemetry)=>void}){
 const host=useRef<HTMLDivElement>(null),live=useRef({pose,world,onContact,onBodyChange,onDragStart,onTrackingPose,onTouch,onTelemetry});live.current={pose,world,onContact,onBodyChange,onDragStart,onTrackingPose,onTouch,onTelemetry};const [error,setError]=useState('');
 useEffect(()=>{if(!host.current)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});}catch{setError('3D is unavailable. Enable hardware acceleration or try another browser.');return;}
 const el=host.current;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#e6edf1');el.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.fog=new THREE.Fog('#e6edf1',10,23);const camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(4.3,3.2,6.8);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1.15,0);orbit.enableDamping=true;orbit.minDistance=3;orbit.maxDistance=11;orbit.maxPolarAngle=Math.PI*.49;
 scene.add(new THREE.HemisphereLight(0xffffff,0x74839a,2.6));const light=new THREE.DirectionalLight(0xfff6e4,4);light.position.set(-3,7,4);light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-6,right:6,top:6,bottom:-6});scene.add(light);
 const mat=(c:string)=>new THREE.MeshStandardMaterial({color:c,roughness:.95});const fur=mat('#92705c'),cream=mat('#e8d8be'),mask=mat('#514339'),black=mat('#231f22'),claw=mat('#e8dfcb'),blue=mat('#365d81');
 function ell(parent:THREE.Object3D,m:THREE.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number){const o=new THREE.Mesh(new THREE.SphereGeometry(1,40,28),m);o.position.set(x,y,z);o.scale.set(sx,sy,sz);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(200,200),mat('#dce5ea'));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(10,20,0x9aacb8,0xc4d0d8);grid.position.y=.006;scene.add(grid);
 const rug=new THREE.Mesh(new THREE.CylinderGeometry(1.4,1.4,.05,80),blue);rug.position.y=.03;rug.receiveShadow=true;scene.add(rug);
 const rig=new THREE.Group();scene.add(rig);const boo=new THREE.Group();boo.position.y=-1.1;rig.add(boo);ell(boo,fur,0,.9,0,.56,.76,.43);ell(boo,cream,0,.94,.29,.41,.54,.19);
 // Feet are fixed plush geometry; the model has exactly five actuated channels.
 for(const s of [-1,1]){ell(boo,fur,s*.34,.22,.25,.26,.22,.37);for(let i=0;i<3;i++)ell(boo,claw,s*.34+(i-1)*.095,.2,.57,.035,.045,.12);}
 const head=new THREE.Group();head.position.set(0,1.63,0);boo.add(head);ell(head,fur,0,.31,0,.62,.55,.48);ell(head,cream,0,.31,.32,.54,.43,.22);
 const eyes:THREE.Mesh[]=[];for(const s of [-1,1]){const patch=ell(head,mask,s*.27,.32,.485,.23,.145,.07);patch.rotation.z=s*.25;const eye=ell(head,black,s*.25,.34,.549,.065,.07,.025);eyes.push(eye);ell(head,fur,s*.52,.35,-.02,.16,.19,.15);}
 ell(head,black,0,.21,.55,.105,.065,.065);const smile=new THREE.Mesh(new THREE.TorusGeometry(.12,.012,8,28,Math.PI),black);smile.rotation.z=Math.PI;smile.position.set(0,.14,.547);head.add(smile);
 // Fine surface tufts suggest plush pile without adding extra articulation.
 const tuftGeo=new THREE.SphereGeometry(1,5,4);const tuft=new THREE.InstancedMesh(tuftGeo,fur,550);let seed=73;const rand=()=>{seed=(seed*16807)%2147483647;return seed/2147483647;};const dummy=new THREE.Object3D();for(let i=0;i<550;i++){const a=rand()*Math.PI*2,b=Math.acos(2*rand()-1);dummy.position.set(.565*Math.sin(b)*Math.cos(a),.9+.765*Math.cos(b),.435*Math.sin(b)*Math.sin(a));dummy.scale.set(.018,.035,.018);dummy.rotation.set(rand(),rand(),rand());dummy.updateMatrix();tuft.setMatrixAt(i,dummy.matrix);}boo.add(tuft);
 const arms:THREE.Group[]=[],hands:THREE.Mesh[]=[];for(const s of [1,-1]){const arm=new THREE.Group();arm.position.set(s*.5,1.34,0);boo.add(arm);ell(arm,fur,s*.07,-.35,.015,.19,.49,.2);const hand=ell(arm,fur,s*.07,-.76,.07,.2,.19,.22);for(let i=0;i<3;i++)ell(arm,claw,s*.07+(i-1)*.09,-.84,.22,.032,.105,.04);arms.push(arm);hands.push(hand);}
  const human=new THREE.Group();scene.add(human);const humanMat=mat('#557acc');ell(human,humanMat,0,1.55,0,.17,.2,.17);ell(human,humanMat,0,1,0,.23,.38,.14);for(const side of [-1,1]){ell(human,humanMat,side*.12,.4,0,.08,.4,.09);ell(human,humanMat,side*.3,1,0,.08,.32,.08);}
 const touchMarkers:Record<Zone,THREE.Mesh>={head:ell(head,mat('#96b6b9'),0,.83,.05,.075,.04,.075),belly:ell(boo,mat('#96b6b9'),0,.98,.488,.065,.065,.03),back:ell(boo,mat('#96b6b9'),0,1,-.435,.065,.065,.03)};Object.entries(touchMarkers).forEach(([zone,m])=>{m.userData.touchZone=zone;m.userData.sensorMarker=true;});
 const radarRoot=new THREE.Group();scene.add(radarRoot);const conePoints:THREE.Vector3[]=[];for(let i=0;i<=60;i++){const a=i/60*Math.PI*2;conePoints.push(new THREE.Vector3(Math.sin(a)*Math.sin(Math.PI/3),Math.cos(a)*Math.sin(Math.PI/3),.5));}for(let i=0;i<4;i++){const a=i*Math.PI/2;conePoints.push(new THREE.Vector3(),new THREE.Vector3(Math.sin(a)*Math.sin(Math.PI/3),Math.cos(a)*Math.sin(Math.PI/3),.5),new THREE.Vector3());}const cone=new THREE.Line(new THREE.BufferGeometry().setFromPoints(conePoints),new THREE.LineBasicMaterial({color:0x6c94ba,transparent:true,opacity:.18}));radarRoot.add(cone);
 const table=new THREE.Mesh(new THREE.BoxGeometry(1.9,.45,.8),mat('#b5c5d1'));table.position.set(0,.225,1.12);table.castShadow=true;table.receiveShadow=true;scene.add(table);
 const ball=ell(scene,mat('#d56e46'),1,.63,.8,.18,.18,.18);const stripe=new THREE.Mesh(new THREE.TorusGeometry(.181,.012,8,40),cream);ball.add(stripe);stripe.scale.setScalar(1/.18);
 const target=ell(scene,mat('#d5a438'),0,1.8,2,.065,.065,.065);const ring=new THREE.Mesh(new THREE.TorusGeometry(.13,.012,8,40),mat('#b38726'));target.add(ring);ring.scale.setScalar(1/.065);
 // Low room boundaries contain the ball, and delimit the play area.
 for(const x of [-4.8,4.8]){const wall=new THREE.Mesh(new THREE.BoxGeometry(.08,.13,9.6),mat('#a9b8c3'));wall.position.set(x,.065,0);scene.add(wall);}for(const z of [-4.8,4.8]){const wall=new THREE.Mesh(new THREE.BoxGeometry(9.6,.13,.08),mat('#a9b8c3'));wall.position.set(0,.065,z);scene.add(wall);}
 let frame=0,last=performance.now(),lastReset=-1,lastCamera=-1,px=NaN,pz=NaN,lastContact=0;const vel=new THREE.Vector3(),previous=[new THREE.Vector3(),new THREE.Vector3()];let initialized=false;
 const supportMeshes:THREE.Mesh[]=[];boo.traverse(o=>{if(o instanceof THREE.Mesh&&!(o instanceof THREE.InstancedMesh)&&o.geometry.type==='SphereGeometry'&&!o.userData.sensorMarker)supportMeshes.push(o);});
 let bodyY=1.1,fallSpeed=0,wasFalling=false,dragging=false,pointerId=-1,lastBodyKey='',supportMin=-1.1;
 let touching:Zone|null=null;let servoStates=initialServos(),sampleTime=0,simTime=0;const lastPosition=new THREE.Vector3(),lastVelocity=new THREE.Vector3(),lastOrientation=new THREE.Quaternion();let imuReady=false,lastHardwareReset=-1;const sampleAccel=new THREE.Vector3(),sampleGyro=new THREE.Vector3();let sampleDuration=0,sampleClipped=false;
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),dragPlane=new THREE.Plane(),hit=new THREE.Vector3(),offset=new THREE.Vector3();
 const setRay=(event:PointerEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);};
 const down=(event:PointerEvent)=>{if(event.button!==0||dragging||touching)return;setRay(event);const intersections=ray.intersectObject(boo,true);if(!intersections.length)return;if(live.current.world.hardware.touchMode){const intersection=intersections[0];const local=boo.worldToLocal(intersection.point.clone());const zone=intersection.object.userData.touchZone as Zone|undefined;touching=zone??(local.y>1.5?'head':Math.abs(local.x)<.58&&local.y>.45&&local.y<1.5?(local.z>0?'belly':'back'):null);if(!touching)return;event.preventDefault();event.stopImmediatePropagation();pointerId=event.pointerId;orbit.enabled=false;renderer.domElement.setPointerCapture(pointerId);live.current.onTouch(touching,true);return;}event.preventDefault();event.stopImmediatePropagation();dragging=true;pointerId=event.pointerId;orbit.enabled=false;renderer.domElement.setPointerCapture(pointerId);dragPlane.setFromNormalAndCoplanarPoint(new THREE.Vector3(0,1,0),intersections[0].point);offset.copy(rig.position).sub(intersections[0].point);live.current.onDragStart();live.current.onContact('Holding Boo · move to position, then release to drop.');renderer.domElement.style.cursor='grabbing';};
 const move=(event:PointerEvent)=>{if(!dragging||event.pointerId!==pointerId)return;event.preventDefault();event.stopImmediatePropagation();setRay(event);if(ray.ray.intersectPlane(dragPlane,hit)){const b=live.current.world.body;live.current.onBodyChange({...b,x:THREE.MathUtils.clamp(hit.x+offset.x,-3.5,3.5),z:THREE.MathUtils.clamp(hit.z+offset.z,-3.5,3.5)});}};
 const up=(event:PointerEvent)=>{if(touching&&event.pointerId===pointerId){event.preventDefault();event.stopImmediatePropagation();live.current.onTouch(touching,false);touching=null;orbit.enabled=true;if(renderer.domElement.hasPointerCapture(pointerId))renderer.domElement.releasePointerCapture(pointerId);return;}if(!dragging||event.pointerId!==pointerId)return;event.preventDefault();event.stopImmediatePropagation();dragging=false;orbit.enabled=true;if(renderer.domElement.hasPointerCapture(pointerId))renderer.domElement.releasePointerCapture(pointerId);renderer.domElement.style.cursor='grab';live.current.onBodyChange({...live.current.world.body,lift:0});live.current.onContact('Boo is settling onto the surface.');};
 renderer.domElement.style.cursor='grab';renderer.domElement.addEventListener('pointerdown',down,true);renderer.domElement.addEventListener('pointermove',move,true);renderer.domElement.addEventListener('pointerup',up,true);renderer.domElement.addEventListener('pointercancel',up,true);
 const resize=()=>{camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight);};const observer=new ResizeObserver(resize);observer.observe(el);resize();
 function tick(now:number){const dt=Math.min((now-last)/1000,.04);last=now;const {pose:command,world:w}=live.current;const hw=w.hardware;if(hw.resetSerial!==lastHardwareReset){servoStates=initialServos();lastHardwareReset=hw.resetSerial;imuReady=false;}simTime+=dt;servoStates=servoStates.map(s=>stepServo(s,command[s.key],hw.servos[s.key],hw.servoSpeed*(hw.voltage/6),hw.voltage,dt));const p=Object.fromEntries(servoStates.map(s=>[s.key,jointAngle(s.key,s.angle)])) as Pose;
 human.visible=hw.human.enabled;human.position.set(hw.human.x,0,hw.human.z);human.rotation.y=hw.human.moving?Math.sin(simTime*3)*.12:0;Object.entries(touchMarkers).forEach(([zone,m])=>{const active=hw.touch[zone as Zone];m.visible=hw.touchMode||active;(m.material as THREE.MeshStandardMaterial).color.set(active?'#2dd792':'#96b6b9');(m.material as THREE.MeshStandardMaterial).emissive.set(active?'#08704c':'#000000');});
 head.rotation.set(THREE.MathUtils.degToRad(p.tilt),THREE.MathUtils.degToRad(p.turn),0,'YXZ');arms[0].rotation.x=-THREE.MathUtils.degToRad(p.left);arms[1].rotation.x=-THREE.MathUtils.degToRad(p.right);eyes.forEach(e=>{e.scale.y=.07*Math.max(.045,1-p.lids/100);});target.position.set(w.targetX,w.targetY,2);
 if(w.reset!==lastReset||w.ballX!==px||w.ballZ!==pz){ball.position.set(w.ballX,.63,w.ballZ);vel.set(0,0,0);lastReset=w.reset;px=w.ballX;pz=w.ballZ;initialized=false;}
 if(w.camera!==lastCamera){camera.position.set(4.3,3.2,6.8);orbit.target.set(0,1.15,0);lastCamera=w.camera;}
  const b=w.body;rig.rotation.set(THREE.MathUtils.degToRad(b.pitch),THREE.MathUtils.degToRad(b.yaw),THREE.MathUtils.degToRad(b.roll),'YXZ');rig.position.set(b.x,0,b.z);scene.updateMatrixWorld(true);
 const bodyKey=JSON.stringify([p,b.x,b.z,b.pitch,b.yaw,b.roll]);if(bodyKey!==lastBodyKey){supportMin=Infinity;for(const m of supportMeshes){const ext=sphereExtents(m.matrixWorld),e=m.matrixWorld.elements;const bottom=e[13]-ext.y;let surfaceOffset=0;if(Math.hypot(e[12],e[14])<1.4+Math.max(ext.x,ext.z))surfaceOffset=Math.max(surfaceOffset,.055);if(e[12]+ext.x>-.95&&e[12]-ext.x<.95&&e[14]+ext.z>.72&&e[14]-ext.z<1.52)surfaceOffset=Math.max(surfaceOffset,.45);supportMin=Math.min(supportMin,bottom-surfaceOffset);}lastBodyKey=bodyKey;initialized=false;}
 const groundY=-supportMin;const targetY=groundY+b.lift+(dragging?.65:0);if(bodyY<targetY){bodyY=targetY;fallSpeed=0;}else if(bodyY>targetY+.0001){const next=advanceDrop(bodyY,fallSpeed,targetY,dt);bodyY=next.y;fallSpeed=next.v;wasFalling=true;}else{fallSpeed=0;if(wasFalling&&!dragging){live.current.onContact('Boo has landed.');wasFalling=false;}}rig.position.y=bodyY;scene.updateMatrixWorld(true);
 if(w.tracking){const localTarget=boo.worldToLocal(target.position.clone()).sub(new THREE.Vector3(0,1.94,0));const turn=THREE.MathUtils.clamp(THREE.MathUtils.radToDeg(Math.atan2(localTarget.x,localTarget.z)),-65,65),tilt=THREE.MathUtils.clamp(-THREE.MathUtils.radToDeg(Math.atan2(localTarget.y,Math.hypot(localTarget.x,localTarget.z))),-25,50);if(Math.abs(turn-command.turn)>.2||Math.abs(tilt-command.tilt)>.2||command.lids!==20)live.current.onTrackingPose({...command,turn,tilt,lids:20});}
 hands.forEach((h,i)=>{const hp=h.getWorldPosition(new THREE.Vector3());if(!w.paused){const delta=ball.position.clone().sub(hp),distance=delta.length(),radius=.37;if(distance<radius){if(distance<.001)delta.set(0,0,1);else delta.normalize();ball.position.copy(hp).addScaledVector(delta,radius);const speed=initialized?Math.min(hp.distanceTo(previous[i])/Math.max(dt,.001),3):0;vel.addScaledVector(delta,.4+speed*1.2);if(now-lastContact>550){live.current.onContact(i===0?'Left hand nudged the ball':'Right hand nudged the ball');lastContact=now;}}}previous[i].copy(hp);});initialized=true;
 if(!w.paused){const oldY=ball.position.y;vel.y-=9.81*dt;ball.position.addScaledVector(vel,dt);const surface=Math.abs(ball.position.x)<.95&&ball.position.z>.72&&ball.position.z<1.52&&oldY>=.625?.63:.18;if(ball.position.y<surface){ball.position.y=surface;vel.y=Math.abs(vel.y)<.15?0:-vel.y*.42;vel.x*=Math.exp(-1.5*dt);vel.z*=Math.exp(-1.5*dt);}for(const axis of ['x','z'] as const){if(Math.abs(ball.position[axis])>4.57){ball.position[axis]=Math.sign(ball.position[axis])*4.57;vel[axis]*=-.6;}}ball.rotation.x+=vel.z*dt/.18;ball.rotation.z-=vel.x*dt/.18;}
 const radarPosition=boo.localToWorld(new THREE.Vector3(0,1,.5));radarRoot.position.copy(radarPosition);radarRoot.quaternion.copy(rig.quaternion);radarRoot.scale.setScalar(hw.range);radarRoot.visible=hw.radarEnabled;const radar=radarState(hw,radarPosition,rig.quaternion);
 const currentPosition=rig.position.clone();const velocity=imuReady?currentPosition.clone().sub(lastPosition).divideScalar(Math.max(dt,.001)):new THREE.Vector3();const linear=imuReady?velocity.clone().sub(lastVelocity).divideScalar(Math.max(dt,.001)):new THREE.Vector3();const accel=accelerometer(linear,rig.quaternion),gyro=imuReady?gyroRate(lastOrientation,rig.quaternion,dt):new THREE.Vector3();lastPosition.copy(currentPosition);lastVelocity.copy(velocity);lastOrientation.copy(rig.quaternion);imuReady=true;
 sampleDuration+=dt;sampleClipped ||= accel.toArray().some(v=>Math.abs(v)>16*9.81)||gyro.toArray().some(v=>Math.abs(v)>2000);sampleAccel.addScaledVector(accel.clone().clampScalar(-16*9.81,16*9.81),dt);sampleGyro.addScaledVector(gyro.clone().clampScalar(-2000,2000),dt);if(simTime-sampleTime>=.1){sampleTime=simTime;const rawAccel=sampleAccel.clone().divideScalar(sampleDuration).toArray(),rawGyro=sampleGyro.clone().divideScalar(sampleDuration).toArray();live.current.onTelemetry({time:simTime,actual:p,servos:servoStates.map(s=>({...s})),accel:rawAccel.map(v=>THREE.MathUtils.clamp(v,-16*9.81,16*9.81)),gyro:rawGyro.map(v=>THREE.MathUtils.clamp(v,-2000,2000)),orientation:[b.pitch,((b.yaw-hw.yawZero+540)%360)-180,b.roll],clipped:sampleClipped,radar,bodyHeight:bodyY});sampleAccel.set(0,0,0);sampleGyro.set(0,0,0);sampleDuration=0;sampleClipped=false;}
 orbit.update();renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
 frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);renderer.domElement.removeEventListener('pointerdown',down,true);renderer.domElement.removeEventListener('pointermove',move,true);renderer.domElement.removeEventListener('pointerup',up,true);renderer.domElement.removeEventListener('pointercancel',up,true);observer.disconnect();orbit.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>m.dispose());}});renderer.dispose();el.removeChild(renderer.domElement);};
 },[]);
 return <div ref={host} className="scene" aria-label="Interactive 3D model of Boo, a five-joint plush sloth">{error&&<p className="error">{error}</p>}</div>;
}





